# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# <3 https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# Site settings
title: Luro02's Blog
email: altenau.lucas@gmail.com
description: For now just a simple blog :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gnarmagon.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# Social Network
twitter_username: luroalive
github_username: gnarmagon

# theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "de-DE"
repository: "gnarmagon/gnarmagon.github.io"
search: true
# Comments
comments:
  provider  : "staticman_v2"
staticman:
  branch    : "master"
reCaptcha:
    enabled: true
    siteKey: 6Lfafj8UAAAAAIKZ9V5xCdni_BMQzhE1Y5OlUOQj
    secret: cz012unO+5gPEaSd2/ktQM0oIhyxLBc9FS0Ao3nkfsSQMOrvi+ITRAIU7ev0U0hbMIA2HdErioQJLFE2/V+VhokjGvwDZKd2JaFbFrSgoqr9rtcoK1YJCKM/4gn7hqxMu2mb0Zbg78ZoQ5P082XvoFa9J8X052q4WhDHgnF/lGg=
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
      comments: true
# Build settings
markdown: kramdown
<<<<<<< HEAD

=======
theme: minimal-mistakes-jekyll
>>>>>>> 96dd90d45f9e575bc5e5fdf23986094b16e17efd
plugins:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock

